In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2)

In [5]:
arr = np.array([1,2,3,4,5,6])
mat = np.array([[1,2,3,4],
                [5,6,7,7]])

In [10]:
np.random.seed(25) # Same seed generates same random number
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [13]:
d=np.arange(5,35)
d

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [19]:
arr*10
arr+c
arr-c
arr/c

array([ 0.12,  0.05, -0.1 , -0.19, -0.15, -0.75])

In [38]:
mat2 = np.arange(8).reshape(2,4)
mat2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
mat*mat2

array([[ 0,  2,  6, 12],
       [20, 30, 42, 49]])

In [39]:
mat2 = np.arange(12).reshape(4,3)
mat2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
mat.dot(mat2)

array([[ 60,  70,  80],
       [123, 148, 173]])

In [41]:
np.dot(mat,mat2)

array([[ 60,  70,  80],
       [123, 148, 173]])